- name: install package
  hosts: node
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.package:
      name: ngnix
      state: present

  - name: start ngnix 
    ansible.builtin.service:
      name: ngnix
      state: started 
      enable: yes


