- name: check conditions
  hosts: local
  connection: local
  vars:
    number: 20
  tasks:
  - name: check wether the given number is less then 10
    ansible.builtin.debug:
      msg: "given number is lessthen  {{ number }}"
    when: number < 10
  
