- name: loops for package install
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: "nginx", state: "latest"}
    - {name: "mysql", state: "absent"}
    - {name: "Zip", state: "absent"}